version: '3.8'

services:
  # PostgreSQL for relational data
  postgres:
    image: postgres:14
    container_name: ecommerce-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ecommerce-net

  # MongoDB for document data
  mongodb:
    image: mongo:6
    container_name: ecommerce-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - ecommerce-net

  # InfluxDB for time-series data
  influxdb:
    image: influxdb:2.6
    container_name: ecommerce-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=ecommerce_metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  influxdb_data: